---
driver_plugin: vagrant
driver_config:
  require_chef_omnibus: true

platforms:
- name: ubuntu-12.04-precise64
  driver_config:
    box: precise64
    box_url: http://files.vagrantup.com/precise64.box
    hostname: "localhost"
  run_list:
  - recipe[apt]
- name: ubuntu-12.04-precise32
  driver_config:
    box: precise32
    box_url: http://files.vagrantup.com/precise32.box
    hostname: "localhost"
  run_list:
  - recipe[apt]
- name: ubuntu-10.04-lucid64
  driver_config:
    box: lucid64
    box_url: http://files.vagrantup.com/lucid64.box
    hostname: "localhost"
  run_list:
  - recipe[apt]
- name: ubuntu-10.04-lucid32
  driver_config:
    box: lucid32
    box_url: http://files.vagrantup.com/lucid32.box
    hostname: "localhost"
  run_list:
  - recipe[apt]
- name: centos-6.4-x64
  driver_config:
    box: centos-6.4-x64
    box_url: http://developer.nrel.gov/downloads/vagrant-boxes/CentOS-6.4-x86_64-v20130427.box
    hostname: "localhost"
# - name: centos-5.6-x64
#   driver_config:
#     box: centos-5.6-x64
#     box_url: http://ftp.cubrid.org/CUBRID_VMImages/Vagrant/vagrant-virtualbox-centos-5.6-x64-minimal.box
#     hostname: "localhost"

suites:
- name: cubrid-9.1.0
  run_list:
  - recipe[cubrid_test]
  - recipe[cubrid_test::demodb]
  - recipe[cubrid_test::php_driver]
  - recipe[cubrid_test::pdo_cubrid]
  attributes: {
    cubrid: {
      version: '9.1.0'
    }
  }
- name: cubrid-8.4.3
  run_list:
  - recipe[cubrid_test]
  - recipe[cubrid_test::demodb]
  - recipe[cubrid_test::php_driver]
  - recipe[cubrid_test::pdo_cubrid]
  attributes: {
    cubrid: {
      version: '8.4.3'
    }
  }
- name: cubrid-8.4.1
  run_list:
  - recipe[cubrid_test]
  - recipe[cubrid_test::demodb]
  - recipe[cubrid_test::php_driver]
  - recipe[cubrid_test::pdo_cubrid]
  attributes: {
    cubrid: {
      version: '8.4.1'
    }
  }
